[package]
name = "myos-ch1"
version = "0.1.0"
edition = "2024"
authors = ["chen"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
tg-sbi = {version = "0.4.2-preview.1", features = ["nobios"]}
